image: hashicorp/terraform:full

definitions:
  caches:
    terraform: .terraform/modules
  steps:
    - step: &plan-step
        name: Plan Terraform Changes
        caches:
          - terraform
        script:
          - ./scripts/terraform-plan.sh
        artifacts:
          - tfplan
    - step: &apply-step
        name: Apply Terraform Changes
        caches:
          - terraform
        trigger: manual
        script:
          - ./scripts/terraform-apply.sh
    - step: &destroy-step
        name: Destroy Environment
        caches:
          - terraform
        script:
          - ./scripts/terraform-destroy.sh

pipelines:
  custom:
    destroy:
      - step: *destroy-step
  default:
    - step: *plan-step
  branches:
    master:
      - step: *plan-step
      - step: *apply-step
