image: hashicorp/terraform:full
pipelines:
  default:
    - step:
        script:
          - terraform init
          - terraform validate
          - terraform plan
  branches:
    master:
      - step:
          script:
            - echo $KEY_FILE | base64 -d > ./gcloud-api-key.json
            - export GOOGLE_APPLICATION_CREDENTIALS=./gcloud-api-key.json
            - export KUBERNETES_SERVICE_HOST=
            - terraform init
            - terraform validate
            - terraform plan
            - terraform apply -input=false -auto-approve
