image: hashicorp/terraform:full

scripts:
  script: &terraform-setup
    - echo $KEY_FILE | base64 -d > ./gcloud-api-key.json
    - export GOOGLE_APPLICATION_CREDENTIALS=./gcloud-api-key.json
    - export KUBERNETES_SERVICE_HOST=
    - terraform init -input=false
  script: &terraform-plan
    - terraform validate
    - terraform plan -out=tfplan -input=false
  script: &terraform-apply
    - terraform apply -input=false -auto-approve tfplan
  script: &terraform-destroy
    - terraform destroy -auto-approve

  

definitions:
  caches:
    terraform: .terraform/modules
  steps:
    - step: &plan-step
        name: Plan Terraform Changes
        caches:
          - terraform
        script: [*terraform-setup, *terraform-plan]
        artifacts:
          - tfplan
    - step: &apply-step
        name: Apply Terraform Changes
        caches:
          - terraform
        trigger: manual
        script: [*terraform-setup, *terraform-apply]
    - step: &destroy-step
        name: Destroy Environment
        caches:
          - terraform
        script: [*terraform-setup, *terraform-destroy]
    

pipelines:
  custom:
    destroy:
      - step: *destroy-step
  default:
    - step: *plan-step
  branches:
    master:
      - step: *plan-step
      - step: *apply-step
