image: hashicorp/terraform:full

definitions:
  caches:
    terraform: ~/.terraform/modules
  steps:
    - step: &terraform-plan
        name: Plan Terraform Changes
        script:
          - echo $KEY_FILE | base64 -d > ./gcloud-api-key.json
          - export GOOGLE_APPLICATION_CREDENTIALS=./gcloud-api-key.json
          - export KUBERNETES_SERVICE_HOST=
          - terraform init -input=false
          - terraform validate
          - terraform plan -out=tfplan -input=false
        artifacts:
          - tfplan
        caches:
          - terraform

pipelines:
  default:
    - step: *terraform-plan
  branches:
    master:
      - step: *terraform-plan
      - step:
          name: Apply Terraform Changes
          trigger: manual
          script:
            - echo $KEY_FILE | base64 -d > ./gcloud-api-key.json
            - export GOOGLE_APPLICATION_CREDENTIALS=./gcloud-api-key.json
            - export KUBERNETES_SERVICE_HOST=
            - terraform init -input=false
            - terraform apply -input=false -auto-approve tfplan
